### ISSUE TITLE
OrderAfterUpdate hook crashes the update process

### ISSUE THREAD

**Issue by Ptosiek** [PrestaShopCorp/ps_eventbus#138]
Hello,

I've been working on a payment integration and faced the issue where the order status (using changeIdOrderState) is not properly updated:
The order current_state is properly set but the process chokes in the middle and order history is not created.
After quite some debugging (new to prestashop here), I found that the hook 'actionObjectOrderUpdateAfter' registered by this module is responsible for it.
I've not dug as far as to see why it happens in this module. I've just commented out the following part:
```
public function hookActionObjectOrderUpdateAfter($parameters)
    {
        $order = $parameters['object'];
        /** @var int $orderId */
        $orderId = $order->id;

        // $this->insertIncrementalSyncObject(
        //    $orderId,
        //    Config::COLLECTION_ORDERS,
        //    date(DATE_ATOM),
        //    $this->shopId
        // );
    }
```
and validated that the order could normally update.

I think the hooks registered here should be fail safe and not crash object update. Definitely some logging would help too.

I don't intent to use the module so I am rather inclined to remove it from now, but if you need some info/data to reproduce it, glad to help.

**Comment by jokesterfr** [comment]
Hi xnegativx!
thank you for your feedback.
`$this->insertIncrementalSyncObject()` method will write the event hook change in an "outbox" table, so the message will be used later on. This is likely the mysql database that takes time to make the write, but there could be a bug as well (this module, PrestaShop Core... hard to say right now).

In which environment are you performing your tests? PHP / PrestaShop?
Could you paste the result of the ps_eventbus healthcheck here? Open https://your.shop.com/index.php?fc=module&module=ps_eventbus&controller=apiHealthCheck to figure it out.

Thank you!

**Comment by xnegativx** [comment]
Sure, running on PrestaShop:
```
{
  "prestashop_version": "1.7.8.7",
  "ps_eventbus_version": "1.9.7",
  "ps_accounts_version": "5.3.1",
  "php_version": "7.4.30",
  "ps_account": false,
  "is_valid_jwt": false,
  "ps_eventbus": true,
  "env": {
    "EVENT_BUS_PROXY_API_URL": "https://eventbus-proxy.psessentials.net",
    "EVENT_BUS_SYNC_API_URL": "https://eventbus-sync.psessentials.net"
  },
  "httpCode": 200
}
```

**Comment by jokesterfr** [comment]
Thank you for your feedback, we will try to get back to you soon.

**Comment by fox-john** [comment]
@Ptosiek This issue has not been answered for a very long time. Since then, several versions of Ps_Eventbus have been released. We invite you to update your module and see if the problem persists.

If this is the case, we invite you to contact us again, either here or via support directly.

In the meantime, I am closing the ticket for prolonged inactivity.
