### ISSUE TITLE
Fatal error ajout au panier

### ISSUE THREAD

**Issue by naatdev** [PrestaShopCorp/ps_eventbus#151]
Hello,
Avec la version 1.10.2 et PS Metrics activé j'ai cette erreur 500 au moment d'ajouter au panier :
![image (6)](https://user-images.githubusercontent.com/40579924/221151419-fc32805b-4233-41ab-91b2-9f69c6b7a8e8.png)

Le problème d'ajout au panier disparait si je désactive event bus

Merci,

Florian

**Comment by jokesterfr** [comment]
Merci pour ce retour, on revient vers vous dès que possible.

**Comment by naatdev** [comment]
Merci pour votre retour, il s'agit d'un Prestashop 1.7.8.2 avec ces specs serveur :

Version du logiciel serveur : Apache
Version de PHP : 7.1.33
Limite de mémoire : 1024M
Temps maximal d'exécution : 300
Taille max. pour envoi de fichiers : 100M

EventBus est en version 1.10.2

**Comment by naatdev** [comment]
Hello, testé aujourd'hui avec la 1.10.6 et le souci est toujours présent, avez vous des avancées sur le sujet?

Merci 😄

**Comment by jokesterfr** [comment]
**PHP 7.1** is not currently supported by the ps_eventbus module.

@naatdev could you retry with at least PHP 7.2.5?
We plan to increase our compatibility (a PR is already available here https://github.com/PrestaShopCorp/ps_eventbus/pull/158 but more time is required to finish it up).

**Comment by naatdev** [comment]
Hello, en passant à une version plus récente de PHP tout semble fonctionner
Merci! :)
