### ISSUE TITLE
2.3.0 installation freeze back office dashboard

### ISSUE THREAD

**Issue by ValentiniVini** [PrestaShopCorp/ps_eventbus#181]
Greetings,
I can't install version 2.3.0 of the module, neither through automatic update, nor through manual installation.
version 2.2.1 (and all previous ones) install correctly.
Installing the 2.3.0 version the prestashop backoffice crashes during the update/installation procedure without emitting any error.
to restart the backoffice I'm forced to exit the dashboard, remove or restore the modules\ps_eventbus folder.
I did the installation tests in a local version of my prestashop.

If you need more information let me know.

**Comment by synicko** [comment]
Thanks a lot for reporting this issue, we fixed it in release v2.3.1
