### ISSUE TITLE
Attempted to call an undefined method named "parseFile" of class "Symfony\Component\Yaml\Parser".  [Symfony\Component\ErrorHandler\Error\UndefinedMethodError 0]

### ISSUE THREAD

**Issue by tone87** [PrestaShopCorp/ps_eventbus#282]
with module active at last version 3.0.7
in some admin page going in error 500 
with this message:

Attempted to call an undefined method named "parseFile" of class "Symfony\Component\Yaml\Parser".

[Symfony\Component\ErrorHandler\Error\UndefinedMethodError 0]

i have prestashop 8.1.5 and php 8.1.28

when module is deactivaed is work all

StackTrace:
Error:
Undefined constant Symfony\Component\Yaml\Yaml::PARSE_CONSTANT

  at vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php:692
  at Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile()
     (vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php:123)
  at Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load()
     (modules/onepagecheckoutps/vendor/prestashop/module-lib-service-container/src/DependencyInjection/ContainerProvider.php:90)
  at PrestaShop\ModuleLibServiceContainer\DependencyInjection\ContainerProvider->get()
     (modules/onepagecheckoutps/vendor/prestashop/module-lib-service-container/src/DependencyInjection/ServiceContainer.php:81)
  at PrestaShop\ModuleLibServiceContainer\DependencyInjection\ServiceContainer->initContainer()
     (modules/onepagecheckoutps/vendor/prestashop/module-lib-service-container/src/DependencyInjection/ServiceContainer.php:61)
  at PrestaShop\ModuleLibServiceContainer\DependencyInjection\ServiceContainer->getService()
     (modules/ps_eventbus/ps_eventbus.php:166)
  at Ps_eventbus->getService()
     (modules/ps_eventbus/ps_eventbus.php:976)
  at Ps_eventbus->insertIncrementalSyncObject()
     (modules/ps_eventbus/ps_eventbus.php:693)
  at Ps_eventbus->hookActionObjectOrderUpdateAfter()
     (classes/Hook.php:1043)
  at HookCore::coreCallHook()
     (classes/Hook.php:418)
  at HookCore::callHookOn()
     (classes/Hook.php:981)
  at HookCore::exec()
     (modules/ets_superspeed/classes/ext/ets_hook:224)
  at Ets_Hook::exec17()
     (override/classes/Hook.php:19)
  at Hook::exec()
     (classes/ObjectModel.php:886)
  at ObjectModelCore->update()
     (modules/etichettespedizioni/classes/GLS.php:174)
  at GLS->creaEtichetta()
     (modules/etichettespedizioni/controllers/admin/AdminGeneraEtichettaController.php:164)
  at AdminGeneraEtichettaController->getEtichetta()
     (modules/etichettespedizioni/controllers/admin/AdminGeneraEtichettaController.php:31)
  at AdminGeneraEtichettaController->renderView()
     (modules/etichettespedizioni/controllers/admin/AdminGeneraEtichettaController.php:17)
  at AdminGeneraEtichettaController->initContent()
     (classes/controller/Controller.php:319)
  at ControllerCore->run()
     (classes/Dispatcher.php:510)
  at DispatcherCore->dispatch()
     (override/classes/Dispatcher.php:40)
  at Dispatcher->dispatch()
     (Backoffice/index.php:95)    

i run url : index.php?fc=module&module=ps_eventbus&controller=apiHealthCheck
and it show :

{
  "prestashop_version": "8.1.5",
  "ps_eventbus_version": "3.0.7",
  "ps_accounts_version": "6.3.2",
  "php_version": "8.1.28",
  "ps_account": true,
  "is_valid_jwt": true,
  "ps_eventbus": true,
  "env": {
    "EVENT_BUS_PROXY_API_URL": "https://eventbus-proxy.psessentials.net",
    "EVENT_BUS_SYNC_API_URL": "https://eventbus-sync.psessentials.net",
    "EVENT_BUS_LIVE_SYNC_API_URL": "https://api.cloudsync.prestashop.com/live-sync/v1"
  },
  "httpCode": 200
}

**Comment by fox-john** [comment]
Hello @tone87,

Thank you for your report issue.

I can't reproduce the problem locally.
It seems from the logs that there is a conflict with another module (onepagecheckoutps).

Do you have an access to a staging environment to reproduce the issue?

You can reach me directly by email: [jonathan.renard@prestashop.com](mailto:jonathan.renard@prestashop.com), or via our Support Team.

**Comment by fox-john** [comment]
Hello @tone87. We have release a [new version](https://github.com/PrestaShopCorp/ps_eventbus/releases/tag/v3.0.8) of Ps_Eventbus. Can you update your Ps_Eventbus to 3.0.8 on your shop, and say me if your problem persist ?

**Comment by tone87** [comment]
Hi, no, the i updated the version but the problema re the same. i will send all via email. thanks

**Comment by fox-john** [comment]
@tone87 Thank you, I am waiting to hear from you by email.

**Comment by tone87** [comment]
i wrong .. with last version is work all good . maybe i needed to clean cache. i notice if something goes wrong
