### ISSUE TITLE
Bug on ps_eventbus v3.0.7

### ISSUE THREAD

**Issue by arasia-shop** [PrestaShopCorp/ps_eventbus#283]
Bugs on v3.0.7 : 

- connexion with client account not possible (error 500) 
- some admin operations impossible like reductions prices modifications 
- add an image for products

Please let's see the following attached error message !
![ps_eventbus_BUG](https://github.com/PrestaShopCorp/ps_eventbus/assets/167291241/aaf177a2-75cb-401b-9849-4480fcd24512)
Module uninstalled on my website. Could you please let us know when the next version solve the issue?

**Comment by fox-john** [comment]
Hello @arasia-shop, Thank you for your feedback. 

Is it possible to have a larger screenshot ? Or, do you have any logs to provide us with on this subject ?

**Comment by arasia-shop** [comment]
It's still not possible to connect with a client account with this new version v3.0.8

**Comment by fox-john** [comment]
@arasia-shop thx you for this test.

Do you have an access to a staging environment to reproduce the issue?

You can reach me directly by email: [jonathan.renard@prestashop.com](mailto:jonathan.renard@prestashop.com), or via our Support Team.
