### ISSUE TITLE
Front controller displays information that should not be public

### ISSUE THREAD

**Issue by rboadalabelgrup** [PrestaShopCorp/ps_eventbus#334]
The apiHealthCheck front controller reveals information such as PrestaShop version and PHP version.

![image](https://github.com/PrestaShopCorp/ps_eventbus/assets/124156176/d210c4a6-7b21-4b37-9f7b-35614022ba00)

**Comment by fox-john** [comment]
@rboadalabelgrup thx for this issues. 

It's planned in a future update to no longer expose this type of data other than by a secured way. We still need to make some changes to our APIs for this.

**Comment by jokesterfr** [comment]
Fixed by https://github.com/PrestaShopCorp/ps_eventbus/releases/tag/untagged-0b582235beba25f9b0b1.
Closing
